(function() {var implementors = {};
implementors["fxa_client"] = [{"text":"impl Fail for <a class=\"enum\" href=\"fxa_client/error/enum.ErrorKind.html\" title=\"enum fxa_client::error::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["fxa_client::error::ErrorKind"]},{"text":"impl Fail for <a class=\"struct\" href=\"fxa_client/error/struct.Error.html\" title=\"struct fxa_client::error::Error\">Error</a>","synthetic":false,"types":["fxa_client::error::Error"]}];
implementors["logins"] = [{"text":"impl Fail for <a class=\"enum\" href=\"logins/enum.ErrorKind.html\" title=\"enum logins::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["logins::error::ErrorKind"]},{"text":"impl Fail for <a class=\"struct\" href=\"logins/struct.Error.html\" title=\"struct logins::Error\">Error</a>","synthetic":false,"types":["logins::error::Error"]},{"text":"impl Fail for <a class=\"enum\" href=\"logins/enum.InvalidLogin.html\" title=\"enum logins::InvalidLogin\">InvalidLogin</a>","synthetic":false,"types":["logins::error::InvalidLogin"]}];
implementors["nss"] = [{"text":"impl Fail for <a class=\"enum\" href=\"nss/enum.ErrorKind.html\" title=\"enum nss::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["nss::error::ErrorKind"]},{"text":"impl Fail for <a class=\"struct\" href=\"nss/struct.Error.html\" title=\"struct nss::Error\">Error</a>","synthetic":false,"types":["nss::error::Error"]}];
implementors["places"] = [{"text":"impl Fail for <a class=\"enum\" href=\"places/error/enum.ErrorKind.html\" title=\"enum places::error::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["places::error::ErrorKind"]},{"text":"impl Fail for <a class=\"struct\" href=\"places/error/struct.Error.html\" title=\"struct places::error::Error\">Error</a>","synthetic":false,"types":["places::error::Error"]},{"text":"impl Fail for <a class=\"enum\" href=\"places/error/enum.InvalidPlaceInfo.html\" title=\"enum places::error::InvalidPlaceInfo\">InvalidPlaceInfo</a>","synthetic":false,"types":["places::error::InvalidPlaceInfo"]},{"text":"impl Fail for <a class=\"enum\" href=\"places/error/enum.Corruption.html\" title=\"enum places::error::Corruption\">Corruption</a>","synthetic":false,"types":["places::error::Corruption"]},{"text":"impl Fail for <a class=\"struct\" href=\"places/types/struct.InvalidVisitType.html\" title=\"struct places::types::InvalidVisitType\">InvalidVisitType</a>","synthetic":false,"types":["places::types::InvalidVisitType"]}];
implementors["push"] = [{"text":"impl Fail for <a class=\"struct\" href=\"push/error/struct.Error.html\" title=\"struct push::error::Error\">Error</a>","synthetic":false,"types":["push::error::Error"]},{"text":"impl Fail for <a class=\"enum\" href=\"push/error/enum.ErrorKind.html\" title=\"enum push::error::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["push::error::ErrorKind"]}];
implementors["rc_crypto"] = [{"text":"impl Fail for <a class=\"enum\" href=\"rc_crypto/enum.ErrorKind.html\" title=\"enum rc_crypto::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["rc_crypto::error::ErrorKind"]},{"text":"impl Fail for <a class=\"struct\" href=\"rc_crypto/struct.Error.html\" title=\"struct rc_crypto::Error\">Error</a>","synthetic":false,"types":["rc_crypto::error::Error"]}];
implementors["sync15"] = [{"text":"impl Fail for <a class=\"enum\" href=\"sync15/enum.ErrorKind.html\" title=\"enum sync15::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["sync15::error::ErrorKind"]},{"text":"impl Fail for <a class=\"struct\" href=\"sync15/struct.Error.html\" title=\"struct sync15::Error\">Error</a>","synthetic":false,"types":["sync15::error::Error"]}];
implementors["sync_manager"] = [{"text":"impl Fail for <a class=\"enum\" href=\"sync_manager/error/enum.ErrorKind.html\" title=\"enum sync_manager::error::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["sync_manager::error::ErrorKind"]},{"text":"impl Fail for <a class=\"struct\" href=\"sync_manager/error/struct.Error.html\" title=\"struct sync_manager::error::Error\">Error</a>","synthetic":false,"types":["sync_manager::error::Error"]}];
implementors["tabs"] = [{"text":"impl Fail for <a class=\"enum\" href=\"tabs/error/enum.ErrorKind.html\" title=\"enum tabs::error::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["tabs::error::ErrorKind"]},{"text":"impl Fail for <a class=\"struct\" href=\"tabs/error/struct.Error.html\" title=\"struct tabs::error::Error\">Error</a>","synthetic":false,"types":["tabs::error::Error"]}];
implementors["viaduct"] = [{"text":"impl Fail for <a class=\"struct\" href=\"viaduct/struct.InvalidHeaderName.html\" title=\"struct viaduct::InvalidHeaderName\">InvalidHeaderName</a>","synthetic":false,"types":["viaduct::headers::name::InvalidHeaderName"]},{"text":"impl Fail for <a class=\"enum\" href=\"viaduct/error/enum.Error.html\" title=\"enum viaduct::error::Error\">Error</a>","synthetic":false,"types":["viaduct::error::Error"]},{"text":"impl Fail for <a class=\"struct\" href=\"viaduct/error/struct.UnexpectedStatus.html\" title=\"struct viaduct::error::UnexpectedStatus\">UnexpectedStatus</a>","synthetic":false,"types":["viaduct::error::UnexpectedStatus"]}];
implementors["webext_storage"] = [{"text":"impl Fail for <a class=\"enum\" href=\"webext_storage/error/enum.ErrorKind.html\" title=\"enum webext_storage::error::ErrorKind\">ErrorKind</a>","synthetic":false,"types":["webext_storage::error::ErrorKind"]},{"text":"impl Fail for <a class=\"struct\" href=\"webext_storage/error/struct.Error.html\" title=\"struct webext_storage::error::Error\">Error</a>","synthetic":false,"types":["webext_storage::error::Error"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()