(function() {var implementors = {};
implementors["autofill"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["ffi_support"] = [{"text":"impl Error for HandleError","synthetic":false,"types":[]}];
implementors["fxa_client"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["interrupt_support"] = [{"text":"impl Error for Interrupted","synthetic":false,"types":[]}];
implementors["logins"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]},{"text":"impl Error for InvalidLogin","synthetic":false,"types":[]}];
implementors["nss"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["places"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]},{"text":"impl Error for InvalidPlaceInfo","synthetic":false,"types":[]},{"text":"impl Error for Corruption","synthetic":false,"types":[]},{"text":"impl Error for InvalidVisitType","synthetic":false,"types":[]}];
implementors["push"] = [{"text":"impl Error for Error","synthetic":false,"types":[]},{"text":"impl Error for ErrorKind","synthetic":false,"types":[]}];
implementors["rc_crypto"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["restmail_client"] = [{"text":"impl Error for RestmailClientError","synthetic":false,"types":[]}];
implementors["sync15"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["sync15_traits"] = [{"text":"impl Error for PayloadError","synthetic":false,"types":[]},{"text":"impl Error for UnacceptableBaseUrl","synthetic":false,"types":[]}];
implementors["sync_manager"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["tabs"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]}];
implementors["viaduct"] = [{"text":"impl Error for InvalidHeaderName","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]},{"text":"impl Error for UnexpectedStatus","synthetic":false,"types":[]}];
implementors["webext_storage"] = [{"text":"impl Error for ErrorKind","synthetic":false,"types":[]},{"text":"impl Error for Error","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()