name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - uses: actions-rs/cargo@v1
            
      - name: Install and Build
        run: |
          git init .
          git remote add origin https://github.com/mozilla/application-services.git
          git pull origin master
          bash ./libs/verify-desktop-environment.sh
          cargo doc --no-deps --document-private-items

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: target/doc # The folder the action should deploy.
